### ISSUE TITLE
language -> i18n

### ISSUE THREAD

**Issue by matteocostantini** [yajra/laravel-datatables-html#102]
### Summary of problem or feature request

Hi, 
i'm writing my app with yajra/laravel-datatables-html . I want use the editor language method, but isn't work, dont translation happened"
It work perfectly if i change the package file src\Html\Editor\Editor.php

### Code snippet of problem
    /**
     * Set Editor's language.
     *
     * @param array $language
     * @return $this
     * @see https://editor.datatables.net/reference/option/i18n
     */
    public function language(array $language)
    {
//$this->attributes['language'] = $language;   
$this->attributes['i18n'] = $language;            <------------------

        return $this;
    }

### System details

- Operating System Win10
- PHP Version 7.1.3
- Laravel Version 5.5
- Laravel-DataTables Version 8.13.7

**Comment by yajra** [comment]
@matteocostantini good catch. It should be `i18n` instead of `language` key as per docs. Would you like to send a PR for the fix?

**Comment by matteocostantini** [comment]
@yajra i'm not able to PR !
