### ISSUE TITLE
Bubble & Inline API

### ISSUE THREAD

**Issue by matteocostantini** [yajra/laravel-datatables-html#104]
### Summary of problem or feature requests

Hi, 
I suggest Bubble & inline API integration in editor html builder using protected methods/properties

I suggest to insert the snippet below in vendor/view/datatables/editor.blade.php
### Code snippet 

```javascript
//
$('#myTable').on( 'click', 'tbody td', function () {
    editor-instance.bubble( this );
} );

...
```
-->

### System details

- Operating System linux
- PHP Version 7.1.3
- Laravel Version 5.6
- Laravel-DataTables Version 8.13.7

**Comment by yajra** [comment]
You can already do this by duplicating `editor.blade.php` like `bubbles.blade.php` and insert the snippet above. After that, use it as the template. Add `->setTemplate('datatables::bubbles')` on the chain as last method call.

**Comment by Benoit75** [comment]
Hello, 
@matteocostantini , did you manage to get it works ? 
@yajra is it the same mecanism for inline editing (see https://editor.datatables.net/examples/inline-editing/simple.html)
Many thank's

**Comment by matteocostantini** [comment]
Hi,
@Benoit75 , it works with inline and bubble, perfectly!

**Comment by Benoit75** [comment]
Hello, 
@matteocostantini could you provide some example ? i used the last version of laravel-datatables-html (as described in https://yajrabox.com/docs/laravel-datatables/master/editor-tutorial) whitch means that i do not know how to add the specific JS code for inline or bubble. 
Thank's
