### ISSUE TITLE
Multi filter select drop down options missing when state is loaded

### ISSUE THREAD

**Issue by mjducharme** [yajra/laravel-datatables-html#106]
### Summary of problem or feature request

Using infyom generator. Trying to use https://datatables.net/examples/api/multi_filter_select.html with saveState.

The problem is that infyom generator uses serverSide: true (doesn't seem to work at all when I set it to false). When serverSide is true, if you navigate away the data table and back again, when saveState reloads the state, it cause the JSON to be filtered based on the previous state and then the filter drop down only shows one item, the last one displayed.

### Code snippet of problem

app/DataTables/OphourDataTable.php

``` php
<?php

namespace App\DataTables;

use App\Models\Ophour;
use Yajra\DataTables\Services\DataTable;
use Yajra\DataTables\EloquentDataTable;

class OphourDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable($query)
    {
        $dataTable = new EloquentDataTable($query);

        return $dataTable->addColumn('action', 'ophours.datatables_actions');
    }

    /**
     * Get query source of dataTable.
     *
     * @param \App\Models\Ophour $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(Ophour $model)
    {
        return $model->newQuery()->with(['hotspot','weekday']);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->addAction(['width' => '120px', 'printable' => false])
            ->parameters([
                'dom'       => 'Bfrtip',
                'stateSave' => true,
		'orderFixed' => [[ 0, 'asc' ]],
	        'order' => [[ 1, 'asc' ]],
		'rowGroup' => [ 'dataSrc' => 'hotspot.displayname' ],
                'buttons'   => [
                    ['extend' => 'create', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'export', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'print', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'reset', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'reload', 'className' => 'btn btn-default btn-sm no-corner',],
                ],	
		'initComplete' => view('ophours.filters'),
            ]);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
		    ['data' => 'hotspot.displayname', 'title' => 'Hotspot', 'visible' => false],
			['data' => 'weekday.name', 'name' => 'weekday_id', 'title' => 'Weekday', 'searchable' => false],
			['data' => 'weekday.name', 'name' => 'weekday.name', 'title' => 'Weekday Name', 'visible' => false],
            'open',
            'close'
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'ophoursdatatable_' . time();
    }
}
```

ophours.filters.blade.php (apologies for the wonky formatting, I accidentally used tabs)

``` js
function () {

	        var state = this.api().state.loaded();
		if (state) {
               this.api().columns(0).every( function () {
                var column = this;
                var div = $('<div class="form-group col-sm-6" style="text-align:left; padding-top: 3px;"><label for="hotspot_filter">Filter for Hotspot:</label>&nbsp;<select id="hotspot_filter" class="form-control"><option value=""></option></select></div>').prependTo( "#dataTableBuilder_filter" )
		var select = div.find("select");
                select.on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
 
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
				
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
				
		select.val(column.search().slice(1, -1).replace('\\', ''));
            } );
	}
        }
```

### System details

- Windows 10
- PHP 7.3.5
- Laravel Version 5.8.33
- Laravel-DataTables HTML 4.5.4

**Comment by mjducharme** [comment]
I have tried setting serverSide to false in parameters, however that results in the table not loading at all. I think that is where the problem is though - shouldn't it still work with serverSide: false?

**Comment by yajra** [comment]
Need to review this but I think the package forces the script generated to use `serverSide: true, processing: true`. Can you inspect the generated script on your side to verify?

**Comment by mjducharme** [comment]
I am able to manually set serverSide to false (and also tried processing to false), and those do take effect (I can see on the page when I view the source after browsing to it), but then the table does not appear to load at all. I can see in the firefox inspector that it doesn't even seem to try to load the ajax data at all if I set serverSide to false. It is using the minifiedAjax method which has some special treatment if serverSide is set to true, and I'm guessing that special behavior isn't working quite as intended?

**Comment by yajra** [comment]
Oh I think we have some misunderstanding here. If you want to use ajax data, serverSide should always be set to true for it to load. You only use serverSide false when the data is already loaded on html afaik.

**Comment by mjducharme** [comment]
Hi, is this actually the case?  There are examples like this: https://datatables.net/examples/data_sources/ajax.html

That uses ajax but serverSide is not true in that case. In that case the ajax shows all records unfiltered instead of filtering, the filtering is done by the client. That is what I am trying to do but is not working, however with your implementation when I set serverSide to false it no longer makes the request to load the ajax data.

**Comment by yajra** [comment]
OIC, completely forgot about that. I think data sources is not yet fully supported. Maybe try setting pageLength to -1 to force the package to load all the records? Will try to experiment on my side too.

**Comment by yajra** [comment]
Manage to make it work. Just chain the following on your builder.

```php
    ->ajax(route('admin.users.index'))
    ->serverSide(false)
    ->processing(false)
```

**Comment by mjducharme** [comment]
Thank you so much for your help, that works perfectly!
