### ISSUE TITLE
Add Parameter in builder

### ISSUE THREAD

**Issue by backids99** [yajra/laravel-datatables-html#113]
### Summary of problem or feature request

please change it, to generate script with parameter

**yajra/laravel-datatables-html/src/Html/Builder.php**
### Code snippet of problem
    protected function makeDataScript(array $data)
    {
        $script = '';
        foreach ($data as $key => $value) {
            $script .= PHP_EOL . "data.{$key} = '{$value}';";
        }

        return $script;
    }

   TO:

    protected function makeDataScript(array $data)
    {
        $script = '';
        foreach ($data as $key => $value) {
            $script .= PHP_EOL . "data.{$key} = {$value};";
        }

        return $script;
    }

**Comment by yajra** [comment]
Almost all of the DTs options are now available in the fluent builder. You can also use `->parameters([...])` if you want to use a plain array.
