### ISSUE TITLE
Any documentation or examples on using Html\Options\Plugins\Responsive.php?

### ISSUE THREAD

**Issue by jhoffmann** [yajra/laravel-datatables-html#120]
### Summary of problem or feature request

I'm trying to stick to Service Providers for a project, but I can't see to find any docs or examples on using the Responsive class instead of raw javascript.

This is what I've got so far, but I don't see a way to add a handlebars template.

```
    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->setTableId('proposals-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->dom('Bfrtp')
                    ->responsive([
                        'details' => [
                            'display' => 'column',
                            'type' => 'inline'
                        ]
                    ])
                    ->orderBy(1)
                    ->buttons(
                        Button::make('create'),
                        Button::make('export'),
                        Button::make('print'),
                        Button::make('reload')
                    );
    }
```

### System details

- Operating System Alpine Linux 3.11.3
- PHP Version 7.3.14
- Laravel Version 6.2
- Laravel-DataTables Version
        "yajra/laravel-datatables-buttons": "^4.8",
        "yajra/laravel-datatables-html": "^4.20",
        "yajra/laravel-datatables-oracle": "^9.0"

**Comment by yajra** [comment]
I suggest you use an IDE for an autocomplete support of methods. See attached screenshot for list of available methods. 

![image](https://user-images.githubusercontent.com/2687997/73703041-a5da4d80-4729-11ea-8406-6b09ab25a529.png)

Unfortunately, I don't have any examples yet.

**Comment by yajra** [comment]
To add, I also added the doc link when you drill down on the method. This might help you browse the library docs easily.

```php
    /**
     * Set responsive option value.
     *
     * @param bool|array $value
     * @return $this
     * @see https://datatables.net/reference/option/responsive
     */
    public function responsive($value = true)
    {
        $this->attributes['responsive'] = $value;

        return $this;
    }
```

**Comment by jhoffmann** [comment]
I did manage to adopt the code found in https://github.com/yajra/laravel-datatables/issues/38#issuecomment-546725878, and that works, however I was hoping for a more eloquent (no pun intended) solution.

It works for now, but I'll look at refactoring it later so I'm not copying the callback into each of my app/DataTables.

**Comment by yajra** [comment]
I sometimes add a common functions under DT callbacks namespace in case you're interested in this approach.

```js
$.fn.dataTable.callbacks.drawCallback = function() {
    alert('test');
}
````

```php
->drawCallback('$.fn.dataTable.callbacks.drawCallback')
```

**Comment by jhoffmann** [comment]
That actually helps a lot!
