### ISSUE TITLE
Issue since v4.21 ajax change - looking for recommended way to include base URL query string to ajax calls

### ISSUE THREAD

**Issue by Slivicon** [yajra/laravel-datatables-html#121]
Hi Yajra:

Since commit acf3aeb5c14038fa80163396d56f8794c596382f I have an issue where before this I was getting the base/parent page URL query string parameters appended to the ajax request parameters, so I could override filters/search based on the original URL query string parameters. Since this commit it seems the query string parameters from the base/parent/original page are not appended to the ajax request anymore.

Is there a recommended way I could have the query string parameters showing in the client web browser address bar be appended to ajax requests, so that I can keep doing what I was doing but use this latest version?

- Operating System: Windows Server 2012
- PHP Version: 7.3
- Laravel Version: 5.8.37
- Laravel-DataTables Version: 9.8, laravel-datatables-html v4.21

**Comment by Slivicon** [comment]
I will have to test, but I wonder if I just change my call to `minifiedAjax()` to be `minifiedAjax(url()->full())`, if that will work to restore the functionality.

**Comment by yajra** [comment]
Oh sorry about the changes if it broke your code. I will review the implementation when I got the chance. Let me know if `minifiedAjax(url()->full())` works.

For most cases, I think it's better to add the url on ajax and not set it to empty string.  What I often do now is use the route to avoid such cases like on that commit where export is not working.

```php
->minifiedAjax(route('users.index'))
```

**Comment by yajra** [comment]
I made some testing and using full url will make the behavior same as before the patch. Thanks for that info. Will be included in next release.
