### ISSUE TITLE
Support the Searchpanes

### ISSUE THREAD

**Issue by quanengineering** [yajra/laravel-datatables-html#130]
I think it would be great if you could support the [searchpanes](https://datatables.net/extensions/searchpanes/examples/initialisation/simple.html) feature. 

For now, despite I include all the required css and js for the searchpanes, and enable the option:

```
parameters([
     'searchPane' => true
 ]);
```

It displays no search panel:

![2020-06-08_11-41](https://user-images.githubusercontent.com/8580008/83993236-12d24e00-a97d-11ea-988a-13eb3409a3db.png)

**Comment by yajra** [comment]
That's nice, I wasn't aware of that feature. Does it support server-side processing?

**Comment by quannetwork** [comment]
Yes, the latest release has just added it: https://datatables.net/extensions/searchpanes/#Server-Side-Processing

Seem like it took them 3 years to make it: https://datatables.net/blog/2020-01-13
