### ISSUE TITLE
Column::responsive proposal.

### ISSUE THREAD

**Issue by matteocostantini** [yajra/laravel-datatables-html#149]
Hi,
it's very important to implement Column::responsive function.
I'm using Column::make(null,'')->content('')->addClass('control')->title('')->orderable(false)->searchable(false)->printable(false)->exportable(false)->width('5%'),
But it's important to save time and code weigth.

Thank you!

**Comment by yajra** [comment]
Is there a responsive option for column? It seems like there is no docs for it https://datatables.net/reference/option/columns.responsive?

Maybe what you need is responsivePriority? https://datatables.net/reference/option/columns.responsivePriority

Anyways, PR is welcome for this proposal. Thanks!

**Comment by matteocostantini** [comment]
No it's no priority but it's for reserve a column (first) to pin/unpin the hidden resultset of a responsive table

**Comment by yajra** [comment]
Not familiar with that, can you please send a PR to better visualize your issue. Or provide sample js codes. Thanks!
