### ISSUE TITLE
Unknown format specifier ")" in Builder.php

### ISSUE THREAD

**Issue by sheefa03** [yajra/laravel-datatables-html#157]
![image](https://user-images.githubusercontent.com/83804997/119130051-52daf580-ba55-11eb-8b35-7c13b9833c16.png)

**Comment by yajra** [comment]
You might have overwritten the default scripts view.

**Comment by yajra** [comment]
Just encountered something similar in relation to PHP8++. It was due to `% S` on the label. Please use `&percent;` instead. It is an issue with sprintf on PHP8.
