### ISSUE TITLE
Import all datatables npm packages and build with vite

### ISSUE THREAD

**Issue by matteocostantini** [yajra/laravel-datatables-html#180]
Hi,
im using laravel 9 app.
I want build all datatables npm packages with Vite.

How can build ?? where I Can put all imports ?

**Comment by yajra** [comment]
I experimented on it I think last week, see the links below:

https://github.com/yajra/laravel-datatables-vite
https://yajrabox.com/docs/laravel-datatables/10.0/quick-starter

Still a work in progress and needs more improvement but should be enough to get started I think on a fresh app.
