### ISSUE TITLE
Control styling of table header

### ISSUE THREAD

**Issue by slash-aka-eric** [yajra/laravel-datatables-html#181]
How do I control the styling of table header using this library?
Example:
```
<table>
  <thead class="bg-200 text-900">
	...
  </thead>
</table>
```

**Comment by yajra** [comment]
Atm, there is no way to add a thread class via the builder. However, there is a pending [PR](https://github.com/yajra/laravel-datatables-html/pull/169) that may solve this.

For a workaround, you can still use the standard table markup. Just make sure you are using the correct table id.

**view:**

```php
<table id="users-table">
  <thead class="bg-200 text-900">
	...
  </thead>
</table>
```

**datatable:**

```php
    public function html(): HtmlBuilder
    {
        return $this->builder()
                    ->setTableId('users-table')
```
