### ISSUE TITLE
How we can pass the arguments parameter for the method makeIfCan()

### ISSUE THREAD

**Issue by CWSPS154** [yajra/laravel-datatables-html#197]
https://github.com/yajra/laravel-datatables-html/blob/3aaf1c19eb70713858e0ff88ac872e3386bbb4c1/src/Html/HasAuthorizations.php#L57
Core Class - Illuminate\Foundation\Auth\Access\Authorizable
![image](https://github.com/yajra/laravel-datatables-html/assets/94110956/95234e0a-7fe9-4a2d-be65-d6796b548c2b)
Yajra\DataTables\Html\HasAuthorizations::makeIfCan()
![image](https://github.com/yajra/laravel-datatables-html/assets/94110956/6eb7df0f-3bef-47ee-9e7c-12f95d651ce7)

**Comment by CWSPS154** [comment]
Could you give some example for how to use the method makeIfCan

**Comment by yajra** [comment]
Use case: column or field is only visible for admin?

```php
Column::makeIfCan('admin', 'secret_column'),
```

On Editor,

```php
Select::makeIfCan('admin', 'role')
```

**Comment by CWSPS154** [comment]
@yajra Thank You for you reply.
For me, I have to apply a Gate `Gate::allows('have-access','create_role')` in the makeIfCan, but there is no option to pass the the argument for the gate option

**Comment by yajra** [comment]
You can also use `Column::makeIf(Gate::allows('have-access','create_role'), 'column')`

**Comment by CWSPS154** [comment]
How we can use for a computed column `Column::computed('action')
                ->title(__('datatable.action'))
                ->exportable(false)
                ->printable(false)
                ->width(60),`

**Comment by yajra** [comment]
Computed is just a shortcut for `searchable=false` and `orderable=false`.

**Comment by CWSPS154** [comment]
@yajra When I use this code for action column, it return this error
DataTables warning: table id=permission-table - Requested unknown parameter '6' for row 0, column 6. For more information about this error, please see http://datatables.net/tn/4
