### ISSUE TITLE
Issue with orderColumn in morph relation

### ISSUE THREAD

**Issue by rahul-sharma-jnet** [yajra/laravel-datatables-html#198]
### Summary of the problem or feature request

When a model uses polymorphic relation and in that case if we want to order the data on it. That's not working.

Comments [id, user_id, 'comment'] -> Datatable
User ['id', 'userable_type', 'userable_id']

Userable Type
---------------------
Admin ['id', 'name']
Staff ['id', 'name']

Now I wanted to list of comments and order by name where userable type is Admin.

### Code snippet of problem
```
->orderColumn('name', function ($query, $order) {
    $query->whereHas('user', function (Builder $q) use ($order) {
        $q->whereHasMorph('userable', [Admin::class], function (Builder $q) use ($order) {
            $q->orderBy('name', $order);
         });
      });
})
```

Would you please suggest me best method to resolve this.

### System details
- Operating System
- PHP 8.1
- Laravel 9.0
- @latest

**Comment by yajra** [comment]
I think the most stable solution here and in general when using the package is to manually use join SQL statements. 

To make it easier, maybe try using https://github.com/kirschbaum-development/eloquent-power-joins.

**Comment by rahul-sharma-jnet** [comment]
Yeah, This issue was solved by using Database Query Builder

```
->orderColumn('name', function ($query, $order) {
    $query->join('users', 'users.id', '=', 'comments.user_id')
               ->join('admins', 'admins.id', '=', 'users.userable_id')
               ->orderBy('admins.name', $order)
               ->select('comments.*');
})
```

**Comment by rahul-sharma-jnet** [comment]
Also, could you help me with the default sorting of data I wanted the data table should be loaded as `orderByDesc('updated_at')` Also this applied sorting is removed when we do manual sorting.
