### ISSUE TITLE
Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead

### ISSUE THREAD

**Issue by JorgRios** [yajra/laravel-datatables-html#199]
### Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead

You have to review the dependency with Laravel Collective, the community made a fork of the original repo which is being maintained, https://github.com/LaravelLux/html when will this dependency be updated? to stop throwing the error 

```Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead.```

### Code snippet of problem

I tried to migrate to said package, but it throws me the following error when migrating or trying to uninstall

  ```
  Class "Collective\Html\HtmlServiceProvider" not found
  ```

Reviewing, I saw that there is a lot of dependency on this package which is already abandoned

```php
use Collective\Html\HtmlServiceProvider as CollectiveHtml;
```

### System details

The files involved so far are:

- composer.json
- src\HtmlServiceProvider.php
- src\Html\Builder.php

**Comment by yajra** [comment]
Yes, it was already removed from the latest version of the package.

**Comment by JorgRios** [comment]
> Yes, it was already removed from the latest version of the package.

Thank you very much, I already made the update and it is perfect.
