### ISSUE TITLE
10.8 release brook the applications for ajax

### ISSUE THREAD

**Issue by froiden-chetan** [yajra/laravel-datatables-html#201]
Please revert this MR https://github.com/yajra/laravel-datatables-html/pull/186 it is revert all the changes of https://github.com/yajra/laravel-datatables-html/pull/122

**Comment by medeirosinacio** [comment]
This pull request broke my filters: https://github.com/yajra/laravel-datatables-html/pull/186, please revert

**Comment by yajra** [comment]
Reverted, thanks for reporting.
