### ISSUE TITLE
Column::makeIf is being rudely unrespected by builder

### ISSUE THREAD

**Issue by Arne1303** [yajra/laravel-datatables-html#222]
### Summary of problem

When conditionally displaying a column using `Column::makeIf(...)` the HTML builder is always displaying the column even if the condition is false, which can also lead to js errors.
I think this is unintended behavior, might take some time later to develop a fix but wanted to check if this is really bugged or just meant to be this way.

**Comment by yajra** [comment]
This appears to be a bug and I was able to replicate it. The empty column was not removed when rendering.

Thanks for reporting, please do not hesitate to submit a PR for a fix if possible.
