### ISSUE TITLE
Setting attribute via call method is not working

### ISSUE THREAD

**Issue by ajaybhargav** [yajra/laravel-datatables-html#226]
### Summary of problem or feature request

I am creating buttons using Button::make and setting attributes using call method. But I am getting exception

### Code snippet of problem

```php
            Button::make("pdfHtml5")
                ->text("<i class='fa fa-file-pdf text-125 text-danger'></i> <span class='d-none'>Export to PDF</span>")
                ->className("btn-light-default btn-bgc-white btn-h-outline-primary btn-a-outline-primary")
                ->autoPrint(false)
                ->exportOptions([
                    'columns' => $this->getExportColumns(),
                ])
                ->orientation('landscape')
                ->title($this->getExportTitle())
                ->customize($this->getPdfCustomize()),
```

Getting exception e.g.

```
[2024-09-08 12:13:16] production.ERROR: Method Yajra\DataTables\Html\Button::orientation does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Yajra\\DataTables\\Html\\Button::orientation does not exist.
```

If i define function like this in vendor/yajra/laravel-datatables-html/src/Html/Button.php:

```php
public function orientation(string $or): static
{
        $this->attributes['orientation'] = $or;

        return $this;
}
```

evereything works fine. It was working fine until the recent update.

### System details

- Operating System: Ubuntu 22.04.4 LTS
- PHP Version: 8.3.11
- Laravel Version: 11.x
- Laravel-DataTables Version: v11

**Comment by yajra** [comment]
Thanks for reporting, might be due to the added [macro](https://github.com/yajra/laravel-datatables-html/pull/224) on button builder, which overrides the Fluent class magic call functionality.

I will review it and patch it as soon as I can. Please do not hesitate to submit a PR. Thanks!
