### ISSUE TITLE
Laravel 5.5.* Support

### ISSUE THREAD

**Issue by bestreaction** [yajra/laravel-datatables-html#25]
Laravel 5.5.* Support.

### System details

- Operating System
- PHP Version: 7.0.0+
- Laravel Version: 5.5.*
- Laravel-DataTables Version: ~8.0

**Comment by graemedewe** [comment]
Having same issue

**Comment by yajra** [comment]
It's supported on v3.x. You can also use use a single installer package if you are interested https://github.com/yajra/datatables to lessen the entries on your composer. Thanks!
