### ISSUE TITLE
Not really a issue

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables-html#30]
I am now going to use version 8.0 instead of  6.0 (I was using this in laravel 5.1) and I am wondering, why you separated this module out of the core datatables module.

Soon I will be working on this module to handle datatables-editor button related changes, as I did in version 6.0.

Thanks,
K

**Comment by yajra** [comment]
Not all users uses html & buttons plugins at all, thus separating it will lessen the dependencies on our projects. For instance, not all users uses `fractal` but it is being force to be installed on your project because of dataTables on v6.x.
