### ISSUE TITLE
Builder using an associate array for render name in getColumns array returns Undefined offset: 0 when 

### ISSUE THREAD

**Issue by ghost** [yajra/laravel-datatables-html#43]
Related post: [https://github.com/yajra/laravel-datatables/issues/1512](https://github.com/yajra/laravel-datatables/issues/1512)

Summary: I created a datatable using laravel-datatables but rather than using builder I did it all on the front end and the data was retrieved from server-side. After I got the datatable all working I decided to move the datatable from the front end to the server-side. 

After I got everything moved over and I ran into an issue with how I added the the datatime render information so I can display the datetime in a human readable format and sort by a timestamp. I was not able to get this to display correctly and as @yajra stated that I should try using an associated array. When I did that I was returned an undefined offset: 0 error from Column.php (53).

**Comment by yajra** [comment]
I think this was already fixed in the latest version. Thanks!
