### ISSUE TITLE
Possible issue with callback refactoring in 3.5.0

### ISSUE THREAD

**Issue by lk77** [yajra/laravel-datatables-html#53]
Hello,

callbacks have been refactored in https://github.com/yajra/laravel-datatables-html/pull/49
with this change, quotes are added to the callback because they are not detected as functions, so functions like this can't be used, example :

result in 3.4.0 :
```
"drawCallback":App.initBoostrapConfirmation
```
result in 3.5.0 :
```
 "drawCallback":"App.initBootstrapConfirmation"
```
it cause an error in datatable, fn does not exist, because the callback is a string know and not a valid function. I think the problem is in isCallbackFunction
```
Str::startsWith(trim($value), ['$', '$.', 'function']) || Str::contains($key, 'editor');
```

i don't know if t's a bug or if it's intended, but for me, App.initBootstrapConfirmation is a valid function, and it's seems bizarre to do :
```
function()
{
    App.initBootstrapConfirmation;
}
```
perhaps `['$', '$.', 'function']` needs to be dynamic, defined in the config, to define what is a function and what is not.

thanks

**Comment by yajra** [comment]
@lk77 good point. I think the refactor introduce this bug. Can you please submit a PR on your proposed solution to extract the function list to config? Sorry for the inconvenience.

**Comment by lk77** [comment]
Hello,

i submited a pr for this.

thanks.
