### ISSUE TITLE
Documentation suggests column name will be set to data attribute but it is not

### ISSUE THREAD

**Issue by Namoshek** [yajra/laravel-datatables-html#58]
### Summary of problem or feature request

[In the documentation](https://yajrabox.com/docs/laravel-datatables/master/html-builder-column) it is written that the column `name` attribute will be set to the same value as the `data` attribute if being omitted. This does not seem to be the case though, as can be seen [here](../blob/3.0/src/Html/Builder.php#L351). The `name` attribute is only set (*to a correct value*) if an array index is given. For snippets as given below, it is not set and therefore search and other functions don't work.

### Code snippet of problem

No `name` field:
```php
protected function getColumns()
{
    return [
        ['data' => 'id', 'title' => trans('my.model.id')],
        ['data' => 'name', 'title' => trans('my.model.name')],
        ['data' => 'url', 'title' => trans('my.model.url')],
    ];
}
```

With `name` field (untested but from the code it should have one):
```php
protected function getColumns()
{
    return [
        'id'    => ['title' => trans('my.model.id')],
        'name'  => ['title' => trans('my.model.name')],
        'title' => ['title' => trans('my.model.url')],
    ];
}
```

### System details

- Laravel Version: 5.6
- Laravel-DataTables Version: latest

**Comment by yajra** [comment]
@Namoshek good catch. Will try to patch this as soon as I can. If you can, please do not hesitate to submit a PR. Thanks!

**Comment by Namoshek** [comment]
I already thought about how it could be solved but I couldn't find a nice one-liner, so I gave up. 😞
But I'll have another look in the evening then. 👍
