### ISSUE TITLE
Performance Status

### ISSUE THREAD

**Issue by ilhanaydinli** [yajra/laravel-datatables-html#66]
Hello,
I have 2 questions about this package.
1-Does this package create problems with the html schema and the javascirpt code in terms of performance?
2-Is the html schema and javascript code generated by this package re-created every time the page is opened? Or is it created and cached once?

**Comment by yajra** [comment]
> 1-Does this package create problems with the html schema and the javascirpt code in terms of performance?

None afaik. This just generates a standard jquery-dataTables js script.

> 2-Is the html schema and javascript code generated by this package re-created every time the page is opened? Or is it created and cached once?

No cache.
