### ISSUE TITLE
Filter with date range while using HTML Builder

### ISSUE THREAD

**Issue by joshuachinemezu** [yajra/laravel-datatables-html#67]
### Summary of problem or feature request

I used the HTML Builder for displaying my data, now I want to add two date input fields which are start date and end date that can be used to get the data within a range of time, Please how can I go about this

### System details

- Operating System : Ubuntu 18.4 LTS
- PHP Version : 7.2
- Laravel Version: 5.4
- Laravel-DataTables Version: 8.0

**Comment by yajra** [comment]
Here is an example of how I integrate a `form` data to the request:

```php
    public function html()
    {
        $script = <<<CDATA
var formData = $("#search-fax").find("input, select").serializeArray();
$.each(formData, function(i, obj){
    data[obj.name] = obj.value;
});
CDATA;

        return $this->builder()
                    ->columns($this->getColumns())
                    ->minifiedAjax('', $script)
                    ->parameters([
                        'order'      => [[2, 'desc']],
                        'searching'  => false,
                        'lengthMenu' => [10, 20, 50, 100],
                        'pageLength' => 20,
                        'buttons'    => [],
                    ]);
    }
```

On the form, you can add the input fields for the date range and it will be appended on the request.

**Comment by abedputra** [comment]
> Here is an example of how I integrate a `form` data to the request:
> 
> ```
>     public function html()
>     {
>         $script = <<<CDATA
> var formData = $("#search-fax").find("input, select").serializeArray();
> $.each(formData, function(i, obj){
>     data[obj.name] = obj.value;
> });
> CDATA;
> 
>         return $this->builder()
>                     ->columns($this->getColumns())
>                     ->minifiedAjax('', $script)
>                     ->parameters([
>                         'order'      => [[2, 'desc']],
>                         'searching'  => false,
>                         'lengthMenu' => [10, 20, 50, 100],
>                         'pageLength' => 20,
>                         'buttons'    => [],
>                     ]);
>     }
> ```
> 
> On the form, you can add the input fields for the date range and it will be appended on the request.

Hi, I have the same problem, I try what you told but still not working, the date range not filtering. Can you tell me with an example?

Thank you.

I use 
Laravel 6
PHP Version : 7.2
Laravel-DataTables Version: 9.0
