### ISSUE TITLE
Client side attributes: data-order and data-search

### ISSUE THREAD

**Issue by jfvoliveira** [yajra/laravel-datatables-html#72]
### Summary of problem or feature request

Is it possible to pass data attributes to the client side in order to have data-order and data-search td attributes?
I have a column with a datetime field. I want to show "x days ago", "x weeks ago", etc but sort it by the timestamp and not the display text.
Same with search. I want to search for a date of 2018 and it searches the datetime and not the "x days ago". Is it possible? If so, how? Thanks

### System details

- Windows 10
- PHP 7.1
- Laravel 5.7
- yajra/laravel-datatables-oracle ~8.0

**Comment by yajra** [comment]
I think data-order & data-search is only applicable on client-side. To make it work for the server-side, you just need to set a different data and name on your column defs.

```php
// js
columns: [
  {data: 'created_at_ago', name: 'created_at'},
  ...
]

// server side dataTables
->addColumn('created_at_ago', function($model){
  return $model->created_at->diffForHumans();
});
```

Notes: `data` attribute is used for display while `name` is used for sorting/searching on the server-side.
