### ISSUE TITLE
How can i regex search?

### ISSUE THREAD

**Issue by gjm** [yajra/laravel-datatables-html#89]
### Summary of problem or feature request

How can I force a column search to be regex? I've tried to pass the `search.regex` option in parameters but it has no effect server side... And the column definition api has no regex attribute.

### System details

- Ubuntu 18.10
- PHP Version 7.2
- Laravel Version 5.7
- Laravel-DataTables 8.0

**Comment by yajra** [comment]
If I recall correctly, regex was disabled due to security concerns.
