### ISSUE TITLE
Add support for Laravel 5.8

### ISSUE THREAD

**Issue by gjm** [yajra/laravel-datatables-html#91]
Dependencies from `laravelcollective/html` prevents using the package in Laravel 5.8.

**Comment by vissr** [comment]
There is already a merge request waiting at said package.
https://github.com/LaravelCollective/html/pull/588

So, I would expect this problem to solve itself pretty soon.

**Comment by gjm** [comment]
Thanks. Will be on it.

Gonçalo Marrafa
