### ISSUE TITLE
how to reload datatable in js when we build datatable html from Server side?

### ISSUE THREAD

**Issue by PhanPirang** [yajra/laravel-datatables-html#93]
If I builde datatable via JS, I can call mytable.ajax.reload():

But now we haven't use any javascript! So how can i reload datatable via js?

**Comment by csb346** [comment]
I managed to do that with this: 
`window.LaravelDataTables["usersTable"].ajax.reload(null, false);`

**Comment by MrPalamen** [comment]
it would be nice to add that on the doc
