### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by sanvu88** [yajra/laravel-datatables-html#97]
### Summary of problem
When try install, I received an error message: " Your requirements could not be resolved to an installable set of packages."

### Error
Problem 1
    - Can only install one of: yajra/laravel-datatables-oracle[8.0.x-dev, v9.4.0].
    - Can only install one of: yajra/laravel-datatables-oracle[v9.4.0, 8.0.x-dev].
    - Can only install one of: yajra/laravel-datatables-oracle[8.0.x-dev, v9.4.0].
    - yajra/laravel-datatables-html v4.0.0 requires yajra/laravel-datatables-oracle 8.* -> satisfiable by yajra/laravel-datatables-oracle[8.0.x-dev].
    - Installation request for yajra/laravel-datatables-html 4.0 -> satisfiable by yajra/laravel-datatables-html[v4.0.0].
    - Installation request for yajra/laravel-datatables-oracle (locked at v9.4.0, required as ~9.0) -> satisfiable by yajra/laravel-datatables-oracle[v9.4.0].

### System details

- Operating System: Nginx
- PHP Version: 7.2
- Laravel Version: 5.8
- Laravel-DataTables Version: 9.4.0

**Comment by yajra** [comment]
Maybe try using https://github.com/yajra/datatables all in one installer.

`composer require yajra/laravel-datatables:^1.5`
